### ISSUE TITLE
CDN Support

### ISSUE THREAD

**Issue by dustfeather** [RamonSmit/Nestable2#25]
It would be useful to provide CDN support for this plugin

**Comment by RamonSmit** [comment]
Agree. I will look for new pull requests on the main repo, merge them as good as possible and then I will take a note for a CDN.

**Comment by pjona** [comment]
Let's see what happen: https://github.com/cdnjs/cdnjs/pull/11439

**Comment by RamonSmit** [comment]
Looks like the checks have passed (reviews)
