### ISSUE TITLE
Add first child via 'add' method doesn't add collapse/expand buttons

### ISSUE THREAD

**Issue by RomanBurunkov** [RamonSmit/Nestable2#66]
I've tested add method and found out one issue when adding item with parent_id.
When adding first child to parent with id parent_id, add method doesn't add expand/colapse buttons and further we have no chance to add them from user side. Looks like we should use setParent method which already exist. But I'm not quite sure where to add it.

**Comment by pjona** [comment]
Please open the issue if the problem still exist.
I will make new release after you confirm the solution.
