### ISSUE TITLE
scroll not working

### ISSUE THREAD

**Issue by japontel** [RamonSmit/Nestable2#71]
I try to move an item in a div with scroll, but dont up and dont down scroll when the item is in top or bottom div.

**Comment by pjona** [comment]
@japontel can you provide example on [jsfiddle.net](https://jsfiddle.net/)? If you have some problem with providing example - check last closed issue.

**Comment by japontel** [comment]
https://jsfiddle.net/60uavx5b/2/
if you drag the fist item to place it at the last item, the scroll dont down automaticaly with the mouse cursor.

**Comment by pjona** [comment]
@japontel check this commit: https://github.com/RamonSmit/Nestable2/commit/a122d48d7b6d0854567ecc82087a9d18859d471d and read documentation how to enable this feature. I updated also example: https://jsfiddle.net/60uavx5b/4/
