### ISSUE TITLE
Links are not click-able in Label

### ISSUE THREAD

**Issue by Maqsyo** [RamonSmit/Nestable2#72]
### Expected behavior
I tried to add a link for each element to edit or delete a specific element.

### Actual behavior
On clicking on the a-tags the e.preventDefault() seems to trigger, so that i can't get the on.click event :(

### Steps to reproduce the behavior
```
<div class="dd" id="modal_1500296184866-nestable-list">
  <ol class="dd-list" id="modal_1500296184866-structList-first">
    <li class="dd-item" data-id="1" data-title="test">
      <div class="dd-handle blue white-text">
        test
        <div class="right">
          <a class="pointer white-text margin-r10 modal_1500296184866-struct-edit" data-id="1" title="Bearbeiten">
            <i class="fa fa-pencil" aria-hidden="true"></i>
          </a>
          <a class="pointer white-text modal_1500296184866-struct-delete" data-id="1" title="Löschen">
            <i class="fa fa-trash" aria-hidden="true"></i>
          </a>
        </div>
        <div class="clear-fix"></div>
      </div>
    </li>
  </ol>
</div>
```

**Comment by RomanBurunkov** [comment]
Not sure e.preventDefault() canceling click events.
I have same structure but with buttons stylized to links(Bootstrap btn btn-link ) and don't have any issues with click events.

Also, can you repeat the issue with jsfiddle?
So some one will be able to check it.

**Comment by Maqsyo** [comment]
Thank you for your fast reply!
I could solve this..
i put my a tags INSIDE the dd-handle class and there a-tags aren't working ^^
Thank you anyway :D

So here's the fixed code.. For somebody else ;D

```
<div class="dd" id="modal_1500296184866-nestable-list">
  <ol class="dd-list" id="modal_1500296184866-structList-first">
    <li class="dd-item" data-id="1" data-title="test">
      <div class="right dd-options">
        <a class="pointer white-text margin-r10 modal_1500296184866-struct-edit" data-id="1" title="Bearbeiten">
          <i class="fa fa-pencil" aria-hidden="true"></i>
        </a>
        <a class="pointer white-text modal_1500296184866-struct-delete" data-id="1" title="Löschen">
          <i class="fa fa-trash" aria-hidden="true"></i>
        </a>
      </div>
      <div class="dd-handle blue white-text">
        test
      </div>
    </li>
  </ol>
</div>
```

**Comment by dragonfly4** [comment]
The "fix" of @Maqsyo doesn't work with json lists.

This one below from Rabia does resolve it. In case other people would be looking for the same.

`$('.dd a').on('mousedown', function (event) { event.preventDefault(); return false; });`

https://stackoverflow.com/questions/45279765/jquery-nestable-plugin-item-click-event-not-working-i-have-added-button-in-nest
