### ISSUE TITLE
Drag not working in chrome

### ISSUE THREAD

**Issue by carman8910** [RamonSmit/Nestable2#73]
Im trying enabled Drag functionality,  but i cant, its possible it or not. Tank you

**Comment by RomanBurunkov** [comment]
@carman8910 , can you clarify your situation with more details and also with jsfiddle example?
Issue description is realy vague.

**Comment by carman8910** [comment]
Im sorry.
I have a code using Nestables plugin by David Bushell, it´s works, does not have some functionality that this plugin. Then i try using this version. The problem is that in this version drag functionality does not work, specifically wih chrome, i tried in iexplorer and it works, but chrome fail. Thanks for your help

**Comment by RomanBurunkov** [comment]
@carman8910 I can't confirm that. Drag works for me in all browsers including mobile.

I think you can have some issue with css or html which is not compatible, so add more details about your code or ksfiddle sample.

**Comment by carman8910** [comment]
https://jsfiddle.net/dekkard/uh5eL5sc/
I have probe this code. In IExplorer works fine, in Chrome fail. Chrome version : Versión 59.0.3071.115 (Build oficial) (64 bits)

I dont know what is the problem, but i have tried in the console. onStartEvent function never is fire in my chrome. 

I appreciate your valuable help

Thanks

**Comment by pjona** [comment]
@carman8910 what is your OS? On Mac with Chrome 59.0.3071.109 (Build oficial) (64 bits) it works.

**Comment by RomanBurunkov** [comment]
I have got same 64 bit 59.0.3071.115. And it works, so I'm able to drag elements.

Does your hardware have touch screen?

**Comment by carman8910** [comment]
Yes has touch screeen. my OS is Windows10

**Comment by RomanBurunkov** [comment]
@carman8910 

So this is the issue.

I believe this the same as: https://github.com/RamonSmit/Nestable2/issues/28

**Comment by carman8910** [comment]
Yes, it's the sim problem, i have not tried touching the screen. Thanks so much

**Comment by carman8910** [comment]
How can I fix this problem? or this its not possible?

**Comment by RomanBurunkov** [comment]
So, may be @pjona can help with that, I'm not very familiar with all that touch staff.

**Comment by RomanBurunkov** [comment]
I think the root cause is that the plugin turns off mouse events if found a touch:

```
            var hasTouch = 'ontouchstart' in document;
            if (hasTouch) {
```

**Comment by pjona** [comment]
@RomanBurunkov @carman8910 I'll look at that

**Comment by carman8910** [comment]
Ok the problem it's solve, but the functionality to TouchScreen its off. 
I did initialize hasTouch on false.

**Comment by pjona** [comment]
@carman8910 can you test this demo: https://jsfiddle.net/s5yt9mc4/2/

I tested it with mouse and on phone, but I don't have touch screen + mouse.

**Comment by carman8910** [comment]
I tested the demo, this works! great job!

**Comment by pjona** [comment]
@carman8910 can you test also on Firefox?
