### ISSUE TITLE
Callout remove fade out

### ISSUE THREAD

**Issue by carman8910** [RamonSmit/Nestable2#76]
Exist a callout function to the remove fallout function

**Comment by RomanBurunkov** [comment]
I didn't quite understand the meaning of this.
Sorry about that ;)

**Comment by pjona** [comment]
@carman8910 can you give some more details?

**Comment by RomanBurunkov** [comment]
Probablly the question is about existance of callback function for remove method woth 'fade' option.

```
$('#selectror').nestable('remove', id, 'fade', function(){
  //Do something when animation done.
});
```

**Comment by pjona** [comment]
@carman8910: can you extend your description, or confirm what @RomanBurunkov said?

**Comment by carman8910** [comment]
@RomanBurunkov  yes, that is my question. Its possible use this code in nestable?
$('#selectror').nestable('remove', id, 'fade', function(){
  //Do something when animation done.
});

**Comment by RomanBurunkov** [comment]
@carman8910 ,

I have such functionality in my local version.
I'll try to add this on friday.

**Comment by pjona** [comment]
We added this functionality with [PR #80](https://github.com/RamonSmit/Nestable2/pull/80).
