### ISSUE TITLE
How do I trigger a double click event on an element?

### ISSUE THREAD

**Issue by s1lver** [RamonSmit/Nestable2#83]
```
$('.dblclick').dblclick(function () {
    console.log($(this));
  });
```
This code does not work...

**Comment by RamonSmit** [comment]
Is it a dynamic created element?

**Comment by s1lver** [comment]
So, I already tried. But there is no effect

**Comment by RamonSmit** [comment]
In that case I'm going to ask @pjona if he can take a little sneekpeek in here

**Comment by s1lver** [comment]
If you use **unbind ()**, then the whole list breaks down

```
$(document).unbind().on('dblclick', ".dblclick", function() {
    console.log('Dblclick');
  });
```

**Comment by s1lver** [comment]
https://jsfiddle.net/4vogfw6o/2/

Dblclick on the 16 item

**Comment by s1lver** [comment]
Hi!
The problem is solved by setting the timeouts.
